### ISSUE TITLE
Icon no show in Vab or SPH (toolbar and clickthrought installed)

### ISSUE THREAD

**Issue by Massetstephane** [linuxgurugamer/PartAngleDisplay#3]
HI!
It had been a while since I had relaunched KSP since I was looking for my new job as an Informatique Support technician, 
I found a training course from 02/07 to 08/07 2022, before I have a little time to test 1.12.3.
I did not retest my mods, but I reinstall what I had from you :) on version 1.10 and 1.11
And So, I installed Part tool display, so I don't have an icon in the VAB and the SPH, and the plugindata folder was not created as well as the setting.cfg file.
Mod installed to retrieve my  mods(1.10 1.11 setup) see below
I configured Unity in 1.12 (Partools) I will test on my ksp1.12.3 unity folder with just test PartangleDisplay.
to see if there is a conflict with the mods installed
![folder](https://user-images.githubusercontent.com/70191880/146666766-b6bd8cd1-3cbc-43e4-8ae9-040bedb74c74.jpg)

edit 👍 work with mod listed below
with the UNITY folder my mod, so there is a conflict mod with other in previous picture.
![folderUNITY](https://user-images.githubusercontent.com/70191880/146667542-cda84be8-3f2a-42f8-ad99-dfb1f657badf.jpg)

**Comment by linuxgurugamer** [comment]
First, would be better to post on the forums, since there are lots of other people who can help.
Second, you are probably missing a dependency, not sure what you mean by Unity folder.
Third, would be best to use CKAN to install, it makes sure things are installed properly with all the necessary dependencies

**Comment by Massetstephane** [comment]
hi ! 
my unity folder is used for ksp (no mod only mine for test).
it's ok it's work on a basic ksp install  i think there is a mod i have installed cause the problem (main install all mods)
on my main ksp , i will add the mods one by one and see what is wrong.
steph

EDIT
resolved (missing ToadicusTools) thank !
